name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Prepare gradle.properties
        run: |
          mkdir -p $HOME/.gradle
          echo "azisabaNmsUsername=${{ secrets.REPO_USERNAME }}" >> $HOME/.gradle/gradle.properties
          echo "azisabaNmsPassword=${{ secrets.REPO_PASSWORD }}" >> $HOME/.gradle/gradle.properties
          echo "repoUsername=${{ secrets.REPO_USERNAME }}" >> $HOME/.gradle/gradle.properties
          echo "repoPassword=${{ secrets.REPO_PASSWORD }}" >> $HOME/.gradle/gradle.properties
      - name: Download TAB
        run: |
          mkdir libs
          wget https://github.com/NEZNAMY/TAB/releases/download/3.0.2/TAB.v3.0.2.jar -O libs/TAB.v3.0.2.jar
      - name: Deploy
        run: ./gradlew clean test publish
